// Default site content. This is what ships in the build and gets prerendered
// (so SEO/first paint always works). The admin saves overrides to content.json
// on the server; the ContentProvider merges those over these defaults at runtime.
export const defaultContent = {
  branding: {
    brandName: 'Vorkhive',
    brandTag: 'CRM · HR · PAYROLL',
    logoImage: '', // empty -> show the "V" mark; otherwise an uploaded image URL
  },
  seo: {
    title: 'Vorkhive — Singapore HR & Payroll Software (HRMS)',
    description: 'The all-in-one HRMS for Singapore. Run leave, claims, attendance, payroll and CPF compliance in one platform. MOM-ready. Start free — no card.',
  },
  ui: {
    nav: { home: 'Home', platform: 'Platform', features: 'Features', pricing: 'Pricing', faq: 'FAQ', customers: 'Customers', contact: 'Contact' },
    signIn: 'Sign in',
    startFree: 'Start free',
    language: 'Language',
  },
  contact: {
    phone: '+6587007621',     // tel: format
    whatsapp: '6587007621',   // wa.me format (digits only)
    email1: 'samuel@vorkhive.com',
    email2: 'enquires@vorkhive.com',
  },
  hero: {
    eyebrow: 'HR · Payroll · CPF Compliance',
    headlineLead: 'HR & payroll software built for ',
    headlineAccent: 'Singapore teams.',
    subtitle: 'Vorkhive is the all-in-one HRMS for Singapore. Run leave, claims, attendance, payroll and CPF compliance from one platform — with employee self-service your whole team actually enjoys using. MOM-ready out of the box.',
    ctaPrimary: 'Start free — no card needed',
    ctaSecondary: 'Book a 15-min demo',
    trustLine: 'CPF & MOM compliant · Bank-grade security · Live in a day',
  },
  logos: {
    caption: 'Trusted by 10,000+ teams across Singapore & the region',
    items: ['Acme Corp', 'Globex', 'Soylent', 'Initech', 'Umbrella'],
  },
  intro: {
    heading: 'What is Vorkhive?',
    body1: 'Vorkhive is a Singapore-compliant HR management system (HRMS) that brings leave, claims, attendance, payroll and CPF compliance together in a single platform. Instead of juggling email approvals, paper claim forms and a payroll spreadsheet, Singapore SMEs run their entire people operation from one login — with employee self-service for staff and automatic CPF calculations for HR.',
    body2: 'Explore the platform by area: leave management, claims, payroll & CPF, and attendance.',
  },
  problem: {
    eyebrow: 'The HR admin trap',
    heading: 'Leave on email. Claims on paper. Payroll in a spreadsheet.',
    sub: 'When every HR task lives somewhere different, compliance gets risky, staff chase HR for answers, and payroll day becomes a scramble.',
    items: [
      { icon: '📨', title: 'Leave stuck in inboxes', text: "Approvals get lost in email, balances live in someone's head, and nobody knows who's off next week." },
      { icon: '🧾', title: 'Claims on paper', text: 'Receipts pile up, reimbursements slip, and finance reconciles everything by hand at month end.' },
      { icon: '⚠️', title: 'CPF & compliance risk', text: 'CPF contributions, MOM leave rules and IRAS filing are easy to get wrong when payroll runs off a manual spreadsheet.' },
    ],
  },
  pillars: {
    eyebrow: 'One HRMS, every HR job',
    heading: 'Leave, claims, payroll & CPF in one platform',
    sub: 'Add an employee once and everything connects — attendance, leave, claims and pay all run off the same record.',
    items: [
      { tag: 'People & Leave', icon: '🌴', title: 'Leave management & self-service', text: 'Staff apply for leave, view balances and browse the directory themselves — no HR back-and-forth.', bullets: ['MOM-aligned leave entitlements', 'Approvals & balances in real time', 'Staff directory & profiles'], moreLabel: 'See self-service →' },
      { tag: 'Payroll & Claims', icon: '💰', title: 'Singapore payroll with CPF', text: 'Run payroll with CPF calculated automatically, and let staff submit expense claims from their phone.', bullets: ['Automatic CPF calculations', 'Digital payslips & IRAS-ready filing', 'Expense claims & approvals'], moreLabel: 'See compliance →' },
      { tag: 'Time & Growth', icon: '📈', title: 'Attendance, training & appraisals', text: 'Capture attendance, manage schedules, and keep training and performance reviews in one place.', bullets: ['Attendance & schedules', 'Training records', 'Appraisals & surveys'], moreLabel: 'See pricing →' },
    ],
  },
  features: {
    heading: 'Why Singapore teams choose Vorkhive',
    items: [
      { eyebrow: 'Employee self-service', title: 'One app for every HR request', text: 'From the Command Centre, every employee applies for leave, submits a claim, views payslips, clocks attendance and completes training — without raising a single ticket to HR.', bullets: ['One dashboard, every HR action', 'Mobile-first, zero training needed', 'HR workload drops overnight'] },
      { eyebrow: 'Singapore compliance', title: 'CPF, MOM & IRAS handled for you', text: 'Vorkhive keeps CPF contributions, statutory leave and IRAS filing aligned with Singapore requirements — so you run payroll with confidence instead of cross-checking circulars.', bullets: ['CPF contributions auto-calculated', 'MOM-aligned leave policies', 'IRAS-ready year-end reporting (IR8A)'] },
    ],
  },
  metrics: [
    { num: '40%', lab: 'Less HR admin' },
    { num: '1 day', lab: 'Average setup time' },
    { num: '10k+', lab: 'Teams onboard' },
    { num: '99.99%', lab: 'Platform uptime' },
  ],
  steps: {
    eyebrow: 'Get started',
    heading: 'Set up your HRMS in three steps',
    sub: 'No lengthy implementation, no consultants. Most Singapore teams are live within a day.',
    items: [
      { title: 'Import your staff', text: 'Bring your team in from a spreadsheet and set leave entitlements in a few clicks.' },
      { title: 'Switch on self-service', text: 'Employees apply for leave, submit claims and view payslips from day one.' },
      { title: 'Run compliant payroll', text: 'Process pay with CPF handled automatically — and hand HR its time back.' },
    ],
  },
  testimonials: {
    eyebrow: 'Loved by HR teams',
    heading: 'Singapore teams that ditched the spreadsheets',
    items: [
      { quote: 'Leave and claims used to be a daily email pile. Now staff self-serve and our HR exec got a full day back every week.', initials: 'SK', name: 'Sarah Kline', role: 'Ops Director, VibeMedia' },
      { quote: 'Payroll with CPF used to terrify me. Vorkhive calculates it automatically and the payslips just go out. It’s a ten-minute job now.', initials: 'MJ', name: 'Marcus Johnson', role: 'Founder, ScaleUp Tech' },
      { quote: 'The team adopted it in days — it feels like a consumer app, not a clunky HR system. Onboarding new hires is effortless.', initials: 'EP', name: 'Elena Patel', role: 'VP of People, CloudSync' },
    ],
  },
  pricing: {
    eyebrow: 'Pricing',
    heading: 'HRMS pricing for Singapore teams',
    sub: "One platform for leave, claims, attendance and payroll — for less than you'd pay for any one of them.",
    plans: [
      { name: 'Starter', desc: 'For small teams putting HR on autopilot.', price: 'S$5', period: ' /user / mo', featured: false, badge: '', bullets: ['Up to 5 users', 'Leave & staff directory', 'Claims & attendance', 'Community support'], cta: 'Start free', ctaTo: 'register' },
      { name: 'Growth', desc: 'For growing teams that need payroll & compliance.', price: 'S$6', period: ' /user / mo', featured: true, badge: 'Most popular', bullets: ['Unlimited users', 'Full payroll with CPF', 'Digital payslips & IRAS export', 'Training & appraisals', 'Priority support'], cta: 'Start 14-day trial', ctaTo: 'register' },
      { name: 'Enterprise', desc: 'Advanced security and control for larger organizations.', price: 'S$12', period: ' /user / mo', featured: false, badge: '', bullets: ['Everything in Growth', 'Single Sign-On (SSO)', 'Dedicated success manager', 'Full API access'], cta: 'Contact sales', ctaTo: 'contact' },
    ],
  },
  faq: {
    eyebrow: 'FAQ',
    heading: 'Frequently asked questions',
    sub: 'Common questions about running HR and payroll on Vorkhive in Singapore.',
    items: [
      { q: 'Is Vorkhive compliant with Singapore employment regulations?', a: 'Yes. Vorkhive handles CPF calculations, MOM-aligned leave entitlements and IRAS-ready payroll reporting, so your HR stays compliant with Singapore requirements.' },
      { q: 'What HR tasks can employees do themselves?', a: 'Through self-service, employees apply for leave, submit claims, view payslips, clock attendance, complete training and update their profile — all from one dashboard.' },
      { q: 'How long does it take to set up Vorkhive?', a: 'Most teams are live within a day. You import your staff directory, set leave entitlements and run your first CPF-compliant payroll the same week.' },
      { q: 'Does Vorkhive calculate CPF automatically?', a: 'Yes. Vorkhive calculates employer and employee CPF contributions automatically on every payroll run and produces digital payslips ready for IRAS filing.' },
      { q: 'How much does Vorkhive cost?', a: 'Vorkhive starts at S$5 per user per month (Starter). The Growth plan is S$6 per user per month and includes full payroll with CPF; Enterprise is S$12 per user per month.' },
    ],
  },
  finalCta: {
    heading: 'Give your HR team its time back',
    sub: 'Join 10,000+ teams running leave, claims, payroll and CPF compliance on one HRMS built for Singapore.',
    ctaPrimary: 'Start free — no card needed',
    ctaSecondary: 'Book a demo',
    trustLine: 'No credit card required · Cancel anytime',
  },
  footer: {
    brandText: 'The Singapore-compliant HRMS for leave, claims, attendance and payroll. Run all of HR from one login.',
    columns: [
      { title: 'Platform', links: [{ label: 'HR software Singapore', href: '/hr-software-singapore' }, { label: 'Singapore payroll', href: '/payroll-singapore' }, { label: 'CPF payroll', href: '/cpf-payroll' }, { label: 'Leave management', href: '/leave-management' }, { label: 'Claims management', href: '/claims' }, { label: 'Attendance software', href: '/attendance-software-singapore' }, { label: 'Pricing', href: '/pricing' }] },
      { title: 'Company', links: [{ label: 'About', href: '#' }, { label: 'Careers', href: '#' }, { label: 'Contact', href: '/contact' }, { label: 'Talenox alternative', href: '/talenox-alternative' }, { label: 'Swingvy alternative', href: '/swingvy-alternative' }] },
      { title: 'Guides', links: [{ label: 'All guides', href: '/guides' }, { label: 'CPF contribution rates', href: '/guides/cpf-contribution-rates-singapore' }, { label: 'MOM leave entitlements', href: '/guides/mom-leave-entitlements-singapore' }, { label: 'How to run payroll (SG)', href: '/guides/how-to-run-payroll-singapore' }] },
    ],
    copyright: '© 2026 Vorkhive, Inc. · Singapore. All rights reserved.',
    legal: 'Privacy · Terms · SOC 2 Type II',
  },
  pages: {
    payroll: {
      seo: { title: 'Singapore Payroll Software with CPF | Vorkhive HRMS', description: 'Run Singapore payroll with CPF calculated automatically, digital payslips and IRAS-ready (IR8A) filing. MOM-ready payroll software from Vorkhive.' },
      eyebrow: 'Singapore Payroll',
      h1: 'Singapore payroll software with CPF built in',
      lede: 'Run accurate, MOM-ready payroll for your Singapore team — with CPF contributions calculated automatically, digital payslips, and IRAS-ready year-end filing. No spreadsheets, no manual CPF tables.',
      ctaPrimary: 'Start free — no card needed', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: 'Payroll built for Singapore, not retrofitted', body: ['Most payroll tools treat Singapore as an afterthought. Vorkhive is a Singapore-compliant HRMS first: every pay run accounts for CPF, statutory leave and IRAS reporting the way local regulations expect. Add an employee once and their salary, leave, claims and attendance all feed the same payroll record.'] },
        { h2: 'CPF calculated automatically on every run', body: ['Vorkhive computes both employer and employee CPF contributions for you on each payroll run, so you never maintain contribution tables or worry about wage ceilings and age bands by hand.'], bullets: ['Employer and employee CPF computed on every pay run', 'Ordinary and additional wage handled correctly', 'Itemised digital payslips employees can self-serve'] },
        { h2: 'IRAS-ready filing and digital payslips', body: ['At year end, Vorkhive produces IRAS-ready reporting (IR8A) so submission is a few clicks instead of a manual reconciliation. Throughout the year, every employee gets itemised digital payslips through self-service — no PDFs emailed around.'] },
        { h2: 'One platform — leave, claims and attendance flow into pay', body: ['Because Vorkhive is a full HRMS, approved leave, submitted claims and recorded attendance connect directly to payroll. That means fewer manual adjustments and fewer payday surprises.'] },
        { h2: 'Set up Singapore payroll in three steps', bullets: ['Import your staff and set salaries and entitlements', 'Connect leave, claims and attendance (already built in)', 'Run payroll — CPF and payslips handled automatically'] },
      ],
      faqHeading: 'Singapore payroll FAQ',
      faq: [
        { q: 'Does Vorkhive calculate CPF automatically?', a: 'Yes. Employer and employee CPF contributions are calculated automatically on every payroll run, and the figures appear on each digital payslip.' },
        { q: 'Is Vorkhive payroll IRAS compliant?', a: 'Vorkhive produces IRAS-ready year-end reporting (IR8A), so filing is straightforward.' },
        { q: 'How long does setup take?', a: 'Most Singapore teams are live within a day — import staff, set entitlements, and run your first CPF-compliant payroll the same week.' },
      ],
      relatedHeading: 'Explore more',
      related: [{ label: 'CPF payroll software', href: '/cpf-payroll' }, { label: 'Pricing', href: '/pricing' }, { label: 'The platform', href: '/platform' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    cpf: {
      seo: { title: 'CPF Payroll Software — Automatic CPF Calculation | Vorkhive', description: 'CPF payroll software that calculates employer and employee CPF automatically on every run, with compliant payslips and IRAS-ready (IR8A) reporting.' },
      eyebrow: 'CPF Payroll',
      h1: 'CPF payroll software that calculates contributions for you',
      lede: 'Stop reconciling CPF by hand. Vorkhive works out employer and employee CPF contributions automatically on every payroll run, produces compliant digital payslips, and keeps you ready for IRAS — so payday in Singapore is a few clicks.',
      ctaPrimary: 'Start free — no card needed', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: 'Automatic CPF calculation, every pay run', body: ['CPF is where most Singapore payroll goes wrong — manual tables, missed wage ceilings, the wrong age band. Vorkhive removes the guesswork: it calculates both the employer and employee CPF contribution for each employee automatically, and shows the figures clearly on every payslip.'], bullets: ['Employer and employee CPF computed automatically', 'Ordinary and additional wages handled', 'Contribution figures itemised on each digital payslip'] },
        { h2: 'Kept aligned with CPF rules', body: ['CPF rates, wage ceilings and age bands change over time. Rather than asking your HR team to track every circular, Vorkhive keeps CPF handling current so your pay runs stay compliant without manual updates. Your team focuses on people, not spreadsheets.'] },
        { h2: 'From CPF to IRAS — year-end handled', body: ['CPF and income reporting are connected. Vorkhive carries the same data through to IRAS-ready year-end reporting (IR8A), so what you run during the year is what you file at the end of it — no separate reconciliation.'] },
        { h2: 'CPF is one part of a complete HRMS', body: ["Vorkhive isn't a standalone CPF calculator — it's a full Singapore HRMS where leave, claims, attendance and payroll share one record. That's why CPF “just works”: the numbers come from the same source of truth your team already uses."] },
      ],
      faqHeading: 'CPF payroll FAQ',
      faq: [
        { q: 'Does Vorkhive calculate both employer and employee CPF?', a: 'Yes — both the employer and employee CPF contributions are calculated automatically on every payroll run.' },
        { q: 'Do I need to update CPF rates myself?', a: 'No. Vorkhive keeps CPF handling aligned with current rules so your pay runs stay compliant without manual table updates.' },
        { q: 'Is the CPF data used for IRAS filing?', a: 'Yes. The same payroll data flows into IRAS-ready year-end reporting (IR8A).' },
      ],
      relatedHeading: 'Explore more',
      related: [{ label: 'Singapore payroll software', href: '/payroll-singapore' }, { label: 'Pricing', href: '/pricing' }, { label: 'The platform', href: '/platform' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    leave: {
      seo: { title: 'Leave Management System Singapore | Vorkhive HRMS', description: 'MOM-aligned leave management for Singapore teams. Staff apply for leave and check balances themselves, approvals happen in real time, and leave flows straight into payroll.' },
      eyebrow: 'Leave Management',
      h1: 'Leave management system built for Singapore teams',
      lede: 'Stop running leave on email and spreadsheets. Vorkhive gives every employee self-service leave applications and live balances, gives managers one-tap approvals, and keeps entitlements aligned with Singapore (MOM) rules — with approved leave flowing straight into payroll.',
      ctaPrimary: 'Start free — no card needed', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: 'Self-service leave, zero HR back-and-forth', body: ['When leave lives in email, HR becomes a help desk: balance questions, chasing approvers, manual spreadsheet updates. With Vorkhive, employees apply for leave and see their own balances from one dashboard, and approvers act with a single tap — so HR stops being the middleman.'], bullets: ['Employees apply and check balances themselves', 'One-tap approvals for managers, on any device', 'Live balances — no spreadsheet reconciliation'] },
        { h2: 'MOM-aligned entitlements out of the box', body: ['Annual leave, sick leave, childcare and the other statutory leave types follow Singapore (MOM) rules from day one. Set entitlements once and Vorkhive tracks accrual, carry-forward and balances automatically, so policies stay compliant without manual upkeep.'], bullets: ['Statutory leave types pre-configured for Singapore', 'Accrual, pro-rating and carry-forward handled', 'Custom company leave policies supported'] },
        { h2: 'Leave that connects to payroll and attendance', body: ['Because Vorkhive is a full HRMS, approved leave updates attendance and feeds payroll automatically. No-pay leave adjusts the pay run; there is no separate export or manual tally at month-end.'] },
        { h2: 'A clear view of who is off, when', body: ['Team leave calendars and reporting give managers an at-a-glance view of coverage, so approving leave never means accidentally leaving a team short.'] },
      ],
      faqHeading: 'Leave management FAQ',
      faq: [
        { q: 'Does Vorkhive follow Singapore (MOM) leave rules?', a: 'Yes. Statutory leave types and entitlements follow MOM guidelines, and you can layer your own company policies on top.' },
        { q: 'Can employees apply for leave themselves?', a: 'Yes. Through self-service, staff apply for leave, see live balances and track approvals from one dashboard — no emails to HR.' },
        { q: 'Does approved leave affect payroll?', a: 'Yes. Because leave, attendance and payroll share one record, approved leave (including no-pay leave) flows straight into the pay run.' },
      ],
      relatedHeading: 'Explore more',
      related: [{ label: 'Claims management', href: '/claims' }, { label: 'Singapore payroll', href: '/payroll-singapore' }, { label: 'The platform', href: '/platform' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    claims: {
      seo: { title: 'Claims Management Software Singapore | Vorkhive HRMS', description: 'Let staff submit expense claims from their phone, approve in one tap, and pay through payroll. Vorkhive claims management is built into a Singapore-compliant HRMS.' },
      eyebrow: 'Claims Management',
      h1: 'Claims management software your team will actually use',
      lede: 'Replace paper claim forms and reimbursement chases. With Vorkhive, employees submit expense claims with a photo of the receipt, managers approve in one tap, and approved claims flow into payroll — all inside your Singapore HRMS.',
      ctaPrimary: 'Start free — no card needed', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: 'Submit a claim in seconds, from anywhere', body: ['Expense claims stall when they mean printing a form, stapling a receipt and walking it to finance. Vorkhive lets staff snap a photo of the receipt and submit a claim from their phone in seconds, with categories and notes captured up front.'], bullets: ['Mobile claim submission with receipt photos', 'Clear categories and notes on every claim', 'Status visible to the employee end to end'] },
        { h2: 'One-tap approvals with a full audit trail', body: ['Managers review and approve claims from any device, and every claim keeps a complete record of who submitted, who approved and when. Finance gets clean, auditable data instead of a shoebox of receipts.'], bullets: ['Approve or reject in one tap', 'Complete audit trail on every claim', 'No lost receipts or duplicate submissions'] },
        { h2: 'Approved claims flow into payroll', body: ['Because claims live in the same HRMS as payroll, approved reimbursements can be paid through the next pay run — no separate spreadsheet, no manual transfer list.'] },
        { h2: 'Part of one connected HRMS', body: ['Claims sit alongside leave, attendance and payroll on a single employee record. Add a person once and every HR process — including expense claims — is ready for them.'] },
      ],
      faqHeading: 'Claims management FAQ',
      faq: [
        { q: 'Can employees submit claims from their phone?', a: 'Yes. Staff submit expense claims with a receipt photo from their phone, and can track the status through to approval.' },
        { q: 'How are claims reimbursed?', a: 'Approved claims flow into payroll, so reimbursements can be paid through the next pay run without a separate process.' },
        { q: 'Is there an audit trail for claims?', a: 'Yes. Every claim records who submitted and approved it and when, giving finance a clean, auditable history.' },
      ],
      relatedHeading: 'Explore more',
      related: [{ label: 'Leave management', href: '/leave-management' }, { label: 'Singapore payroll', href: '/payroll-singapore' }, { label: 'The platform', href: '/platform' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    hrSoftware: {
      seo: { title: 'HR Software Singapore — All-in-One HRMS | Vorkhive', description: 'HR software built for Singapore: leave, claims, attendance and payroll with CPF in one HRMS. MOM-ready, employee self-service, live in a day. Start free.' },
      eyebrow: 'HR Software Singapore',
      h1: 'HR software built for Singapore businesses',
      lede: 'Vorkhive is the all-in-one HR software for Singapore SMEs — leave, claims, attendance and payroll with CPF on one platform, with self-service every employee actually uses. MOM-ready out of the box, and most teams are live within a day.',
      ctaPrimary: 'Start free — no card needed', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: 'One HR system instead of five tools', body: ['Most Singapore SMEs run HR across email, spreadsheets, a chat group and a separate payroll tool. Vorkhive replaces all of it: add an employee once and their leave, claims, attendance and payroll all run off the same record — no re-keying, no reconciliation, no version-control chaos.'], bullets: ['Leave, claims, attendance and payroll in one place', 'A single source of truth per employee', 'Employee self-service from day one'] },
        { h2: 'Built for Singapore compliance, not retrofitted', body: ['Generic HR software treats Singapore as an afterthought. Vorkhive is built around CPF, MOM-aligned leave and IRAS reporting from the ground up, so compliance is the default rather than something you bolt on and cross-check by hand.'], bullets: ['Automatic CPF on every payroll run', 'MOM-aligned statutory leave', 'IRAS-ready year-end reporting (IR8A)'] },
        { h2: 'Self-service your whole team will use', body: ['HR stops being a help desk when employees can do things themselves. From one dashboard, staff apply for leave, submit claims, view payslips, clock attendance and complete training — so HR gets its time back and answers stop living in inboxes.'] },
        { h2: 'Live in a day, priced for SMEs', body: ['Import your staff from a spreadsheet, set entitlements, switch on self-service, and run your first compliant payroll the same week. Transparent per-user pricing means you pay for one platform instead of several subscriptions.'] },
      ],
      faqHeading: 'HR software FAQ',
      faq: [
        { q: 'What is the best HR software for Singapore SMEs?', a: 'The best fit is HR software built for local compliance. Vorkhive handles CPF, MOM-aligned leave and IRAS reporting natively, and combines leave, claims, attendance and payroll in one HRMS designed for Singapore teams.' },
        { q: 'Does Vorkhive include payroll?', a: 'Yes. Payroll with automatic CPF is built in — approved leave, claims and attendance flow straight into the pay run.' },
        { q: 'How quickly can we get started?', a: 'Most Singapore teams are live within a day: import staff, set entitlements, and run a compliant payroll the same week.' },
      ],
      relatedHeading: 'Explore more',
      related: [{ label: 'Singapore payroll', href: '/payroll-singapore' }, { label: 'Leave management', href: '/leave-management' }, { label: 'Attendance software', href: '/attendance-software-singapore' }, { label: 'Pricing', href: '/pricing' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    attendance: {
      seo: { title: 'Attendance Software Singapore — Time & Clock-In | Vorkhive', description: 'Attendance and time-tracking software for Singapore teams. Mobile clock-in, real-time timesheets, and attendance that flows straight into leave and payroll.' },
      eyebrow: 'Attendance & Time',
      h1: 'Attendance and time-tracking software for Singapore teams',
      lede: 'Track attendance without spreadsheets or punch cards. Staff clock in from their phone, timesheets build themselves in real time, and the hours flow straight into leave balances and payroll — all inside your Singapore HRMS.',
      ctaPrimary: 'Start free — no card needed', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: 'Mobile clock-in, accurate timesheets', body: ['Employees clock in and out from their phone, and Vorkhive assembles accurate timesheets automatically. No paper, no manual tally, and a clear record managers can trust at the end of the month.'], bullets: ['Mobile clock-in and clock-out', 'Real-time timesheets, built automatically', 'Clear records for every employee'] },
        { h2: 'Attendance that connects to leave and payroll', body: ['Because attendance lives in the same HRMS as leave and payroll, approved leave shows on the timesheet and worked hours feed the pay run directly. There is no separate export and no double entry between systems.'] },
        { h2: 'Visibility for managers, fairness for staff', body: ['Managers get an at-a-glance view of who is in, who is on leave and where the gaps are, while employees get a transparent record of their own hours — so attendance stops being a source of disputes.'] },
        { h2: 'Part of one connected platform', body: ['Attendance is one module of a full Singapore HRMS that also runs leave, claims and CPF payroll. Add a person once and every HR process is ready for them.'] },
      ],
      faqHeading: 'Attendance software FAQ',
      faq: [
        { q: 'Can employees clock in from their phone?', a: 'Yes. Staff clock in and out from their phone, and Vorkhive builds their timesheet automatically in real time.' },
        { q: 'Does attendance feed into payroll?', a: 'Yes. Worked hours and approved leave flow straight into the pay run, with no separate export.' },
        { q: 'Is attendance part of the same platform as payroll?', a: 'Yes. Attendance, leave, claims and payroll share one employee record in Vorkhive.' },
      ],
      relatedHeading: 'Explore more',
      related: [{ label: 'Leave management', href: '/leave-management' }, { label: 'Singapore payroll', href: '/payroll-singapore' }, { label: 'HR software Singapore', href: '/hr-software-singapore' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    vsTalenox: {
      seo: { title: 'Talenox Alternative — Vorkhive HRMS for Singapore', description: 'Comparing HR and payroll software in Singapore? See why teams choose Vorkhive as a Talenox alternative: one HRMS for leave, claims, attendance and CPF payroll.' },
      eyebrow: 'Comparison',
      h1: 'Looking for a Talenox alternative?',
      lede: 'If you are weighing up Singapore HR and payroll tools, here is a fair, no-spin look at where Vorkhive fits — a single HRMS that runs leave, claims, attendance and CPF payroll together, with self-service your whole team uses.',
      ctaPrimary: 'Start free — no card needed', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: 'Why teams compare options', body: ['Singapore has several capable HR and payroll products, Talenox among them. Teams usually start comparing when they want fewer disconnected tools, stronger employee self-service, or one platform that covers leave, claims, attendance and payroll rather than just one or two of them.'] },
        { h2: 'Where Vorkhive focuses', body: ['Vorkhive is a full Singapore HRMS on one record: leave, claims, attendance and payroll with automatic CPF, plus a self-service dashboard employees actually use. The goal is to remove the gaps between separate systems so HR stops re-keying and reconciling.'], bullets: ['Leave, claims, attendance and payroll on one platform', 'Automatic CPF and IRAS-ready (IR8A) reporting', 'Self-service for every employee', 'Most teams live within a day'] },
        { h2: 'How to choose well', body: ['The right tool depends on your team size, how much you value self-service, and whether you want payroll and HR in one place. We would always encourage you to trial more than one option with your own data — start a free Vorkhive trial and compare it directly against your shortlist.'] },
      ],
      faqHeading: 'Talenox alternative FAQ',
      faq: [
        { q: 'Is Vorkhive a good Talenox alternative?', a: 'If you want one HRMS that combines leave, claims, attendance and CPF payroll with strong employee self-service, Vorkhive is worth trialling alongside your shortlist.' },
        { q: 'Does Vorkhive handle CPF and IRAS like other Singapore tools?', a: 'Yes. CPF is calculated automatically on every payroll run and the data flows into IRAS-ready year-end reporting (IR8A).' },
        { q: 'Can I trial Vorkhive with my own data?', a: 'Yes. You can start a free trial, import your staff and compare Vorkhive directly against other options.' },
      ],
      relatedHeading: 'Explore more',
      related: [{ label: 'Swingvy alternative', href: '/swingvy-alternative' }, { label: 'Singapore payroll', href: '/payroll-singapore' }, { label: 'Pricing', href: '/pricing' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    vsSwingvy: {
      seo: { title: 'Swingvy Alternative — Vorkhive HRMS for Singapore', description: 'Evaluating a Swingvy alternative in Singapore? Vorkhive runs leave, claims, attendance and CPF payroll on one HRMS, with self-service every employee uses.' },
      eyebrow: 'Comparison',
      h1: 'Looking for a Swingvy alternative?',
      lede: 'Shortlisting Singapore HR software? Here is a straightforward look at where Vorkhive fits — one HRMS that brings leave, claims, attendance and CPF payroll together, built around local compliance.',
      ctaPrimary: 'Start free — no card needed', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: 'Why teams compare options', body: ['Singapore teams comparing HR platforms — Swingvy included — are usually after one connected system instead of several, better self-service, and payroll that handles CPF without manual work. It is worth comparing a couple of options against your own processes before deciding.'] },
        { h2: 'Where Vorkhive focuses', body: ['Vorkhive is a complete Singapore HRMS on a single employee record: leave, claims, attendance and payroll with automatic CPF, and a dashboard employees use to self-serve. Fewer systems means less re-keying and fewer payday surprises.'], bullets: ['One platform for leave, claims, attendance and payroll', 'Automatic CPF and IRAS-ready (IR8A) reporting', 'Employee self-service from day one', 'Live within a day for most teams'] },
        { h2: 'How to choose well', body: ['Pick based on your team size, your appetite for self-service, and whether you want HR and payroll unified. Trial your shortlist with real data — you can start a free Vorkhive trial and compare it side by side.'] },
      ],
      faqHeading: 'Swingvy alternative FAQ',
      faq: [
        { q: 'Is Vorkhive a good Swingvy alternative?', a: 'If you want a single HRMS covering leave, claims, attendance and CPF payroll with self-service, Vorkhive is worth trialling against your shortlist.' },
        { q: 'Does Vorkhive calculate CPF automatically?', a: 'Yes. Employer and employee CPF are calculated automatically on every payroll run, with IRAS-ready year-end reporting.' },
        { q: 'How long does setup take?', a: 'Most Singapore teams are live within a day — import staff, set entitlements and run a compliant payroll the same week.' },
      ],
      relatedHeading: 'Explore more',
      related: [{ label: 'Talenox alternative', href: '/talenox-alternative' }, { label: 'CPF payroll', href: '/cpf-payroll' }, { label: 'Pricing', href: '/pricing' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    guidesIndex: {
      seo: { title: 'Singapore HR & Payroll Guides | Vorkhive', description: 'Practical guides for Singapore HR and payroll — CPF contribution rates, MOM leave entitlements, and how to run payroll in Singapore. Clear, up-to-date explainers.' },
      eyebrow: 'Guides',
      h1: 'Singapore HR & payroll guides',
      lede: 'Plain-English explainers for the things Singapore employers actually have to get right — CPF, statutory leave and payroll. Each guide links to the official source so you can always verify the current rules.',
      ctaPrimary: 'Start free — no card needed', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: 'Browse the guides', body: ['New guides are added regularly. Start with the essentials below.'], bullets: ['CPF contribution rates in Singapore — how they work', 'MOM leave entitlements for Singapore employees', 'How to run payroll in Singapore, step by step'] },
      ],
      faqHeading: '',
      faq: [],
      relatedHeading: 'Read a guide',
      related: [{ label: 'CPF contribution rates', href: '/guides/cpf-contribution-rates-singapore' }, { label: 'MOM leave entitlements', href: '/guides/mom-leave-entitlements-singapore' }, { label: 'How to run payroll in Singapore', href: '/guides/how-to-run-payroll-singapore' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    guideCpf: {
      seo: { title: 'CPF Contribution Rates in Singapore — How They Work (Guide) | Vorkhive', description: 'A clear guide to how CPF contribution rates work in Singapore: employer vs employee shares, age bands, Ordinary and Additional Wages, and wage ceilings. Verify current figures with the CPF Board.' },
      eyebrow: 'Guide · CPF',
      h1: 'CPF contribution rates in Singapore: how they work',
      lede: 'CPF is where most Singapore payroll goes wrong. This guide explains how contributions are structured — who pays what, how age affects the rate, and which wages count — so you understand the mechanics. Always confirm the exact current figures on the CPF Board website, as rates and ceilings are updated periodically.',
      ctaPrimary: 'Automate CPF with Vorkhive', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: 'Employer and employee both contribute', body: ['For most local employees, a CPF contribution is made up of two parts: an employer share paid on top of salary, and an employee share deducted from wages. Both are remitted to the CPF Board together. The combined rate depends mainly on the employee’s age.'] },
        { h2: 'Rates step down with age', body: ['CPF contribution rates are highest for younger workers and step down across defined age bands as employees get older. Because the bands and percentages are set by the CPF Board and adjusted from time to time, the reliable approach is to apply the current official rate for each employee’s age band rather than memorising a fixed number.'], bullets: ['Rates are banded by the employee’s age', 'Employer and employee shares can differ within a band', 'Senior-worker rates have been rising in recent years'] },
        { h2: 'Ordinary Wages vs Additional Wages', body: ['CPF distinguishes Ordinary Wages (OW) — typically your monthly salary — from Additional Wages (AW) such as bonuses. Each is subject to a ceiling that caps how much wage attracts CPF. Getting OW and AW right is one of the most common manual-payroll mistakes.'], bullets: ['Ordinary Wages: usually monthly salary, subject to the OW ceiling', 'Additional Wages: bonuses and similar, subject to a separate AW ceiling', 'Both ceilings are reviewed periodically by the CPF Board'] },
        { h2: 'Why automation matters', body: ['Because the rate depends on age band, OW/AW classification and current ceilings, manual CPF in a spreadsheet is error-prone. Vorkhive calculates employer and employee CPF automatically on every payroll run and keeps the handling aligned with current rules — so the right amount is computed without you maintaining tables.'] },
        { h2: 'Always verify the current figures', body: ['This guide explains the structure, not a fixed rate card. For the exact percentages, age bands and wage ceilings that apply right now, refer to the official CPF Board website (cpf.gov.sg), which is the authoritative source.'] },
      ],
      faqHeading: 'CPF rates FAQ',
      faq: [
        { q: 'Who pays CPF — the employer or the employee?', a: 'Both. There is an employer contribution paid on top of salary and an employee contribution deducted from wages, remitted to the CPF Board together.' },
        { q: 'Do CPF rates change with age?', a: 'Yes. Contribution rates are banded by the employee’s age and generally step down as employees get older. Use the current official rate for each age band.' },
        { q: 'Where can I find the exact current CPF rates?', a: 'On the CPF Board website, cpf.gov.sg. Rates and wage ceilings are updated periodically, so it is the authoritative source for current figures.' },
        { q: 'Does Vorkhive calculate CPF for me?', a: 'Yes. Vorkhive computes employer and employee CPF automatically on every payroll run and keeps the handling aligned with current rules.' },
      ],
      relatedHeading: 'Related',
      related: [{ label: 'CPF payroll software', href: '/cpf-payroll' }, { label: 'How to run payroll in Singapore', href: '/guides/how-to-run-payroll-singapore' }, { label: 'CPF Board (official)', href: 'https://www.cpf.gov.sg' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    guideLeave: {
      seo: { title: 'MOM Leave Entitlements in Singapore — Employee Guide | Vorkhive', description: 'A guide to statutory leave in Singapore under MOM: annual leave, sick and hospitalisation leave, maternity, paternity and childcare leave. Verify current details on mom.gov.sg.' },
      eyebrow: 'Guide · Leave',
      h1: 'MOM leave entitlements in Singapore: a quick guide',
      lede: 'Singapore’s statutory leave is governed by the Employment Act and administered by the Ministry of Manpower (MOM). This guide summarises the main leave types so you know what to plan for. Entitlements have conditions and are updated over time, so confirm the current rules on mom.gov.sg.',
      ctaPrimary: 'Manage leave with Vorkhive', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: 'Annual (paid) leave', body: ['Employees covered by the Employment Act who have worked at least three months are entitled to paid annual leave that increases with length of service, starting from a statutory minimum in the first year and rising with each year of service. Many employers offer more than the minimum as a benefit.'] },
        { h2: 'Sick leave and hospitalisation leave', body: ['After meeting the qualifying service period, employees are entitled to paid outpatient sick leave and a larger allowance of paid hospitalisation leave, provided the sick leave is certified by a recognised doctor and properly notified to the employer.'], bullets: ['Paid outpatient sick leave once qualified', 'A larger paid hospitalisation leave allowance', 'Medical certification and notification conditions apply'] },
        { h2: 'Maternity, paternity and childcare leave', body: ['Government-supported parental leave includes maternity leave, paternity leave and childcare leave for eligible parents, with conditions around the child’s citizenship, the parents’ employment and length of service. These schemes have been expanded in recent years, so check the current entitlement before applying it.'], bullets: ['Maternity leave for eligible mothers', 'Paternity leave for eligible fathers (recently expanded)', 'Shared and childcare leave subject to conditions'] },
        { h2: 'Keeping leave compliant', body: ['The detail matters: qualifying periods, pro-rating, carry-forward and encashment all affect what an employee is actually owed. Vorkhive applies MOM-aligned leave types and tracks balances, accrual and approvals automatically, so policies stay compliant without manual upkeep.'] },
        { h2: 'Always verify with MOM', body: ['This is a summary, not legal advice. For the precise, current entitlements and conditions, refer to the Ministry of Manpower (mom.gov.sg), which is the authoritative source.'] },
      ],
      faqHeading: 'Singapore leave FAQ',
      faq: [
        { q: 'How much annual leave is required in Singapore?', a: 'Employees covered by the Employment Act are entitled to a statutory minimum of paid annual leave after three months of service, increasing with each year of service. Confirm the current figures on mom.gov.sg.' },
        { q: 'How much paid sick leave do employees get?', a: 'Once qualified, employees are entitled to paid outpatient sick leave and a larger paid hospitalisation leave allowance, subject to medical certification and notification. See MOM for current limits.' },
        { q: 'Where can I confirm the current entitlements?', a: 'On the Ministry of Manpower website, mom.gov.sg, which is the authoritative source for Singapore leave entitlements.' },
        { q: 'Can Vorkhive track statutory leave for me?', a: 'Yes. Vorkhive applies MOM-aligned leave types and tracks balances, accrual and approvals automatically.' },
      ],
      relatedHeading: 'Related',
      related: [{ label: 'Leave management software', href: '/leave-management' }, { label: 'CPF contribution rates', href: '/guides/cpf-contribution-rates-singapore' }, { label: 'MOM (official)', href: 'https://www.mom.gov.sg' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    guidePayroll: {
      seo: { title: 'How to Run Payroll in Singapore — Step-by-Step Guide | Vorkhive', description: 'A step-by-step guide to running payroll in Singapore: gather employee data, calculate gross pay, apply CPF and deductions, pay employees, issue payslips and file with IRAS.' },
      eyebrow: 'Guide · Payroll',
      h1: 'How to run payroll in Singapore, step by step',
      lede: 'Running payroll in Singapore means getting gross pay, CPF, deductions, payslips and IRAS reporting right — every cycle. This guide walks through the process so nothing is missed, and shows where the right software removes the manual work.',
      ctaPrimary: 'Run payroll with Vorkhive', ctaSecondary: 'Book a 15-min demo',
      sections: [
        { h2: '1. Gather accurate employee data', body: ['Start with a clean record for each employee: salary, employment type, start date, bank details and any variable inputs such as approved overtime, claims or unpaid leave for the period. Errors here cascade into the whole run, which is why a single source of truth matters.'] },
        { h2: '2. Calculate gross pay for the period', body: ['Work out each employee’s gross pay including basic salary plus any additional wages such as bonuses, commissions or allowances that apply this cycle. Keep Ordinary Wages and Additional Wages distinct — they are treated differently for CPF.'] },
        { h2: '3. Apply CPF and statutory deductions', body: ['Calculate employer and employee CPF based on each employee’s age band and the current wage ceilings, then apply any other applicable deductions. This is the most error-prone step when done manually.'], bullets: ['Employer and employee CPF by age band', 'Respect the OW and AW ceilings', 'Apply any other statutory or agreed deductions'] },
        { h2: '4. Pay employees and issue payslips', body: ['Pay net salaries on time and give every employee an itemised payslip — itemised payslips are a requirement for employees covered by the Employment Act. Digital self-service payslips save HR from emailing PDFs each month.'] },
        { h2: '5. Keep records and file with IRAS', body: ['Retain payroll records and prepare year-end income reporting for IRAS (IR8A). Doing this from the same data you paid on avoids a separate year-end reconciliation.'] },
        { h2: 'Let software do the heavy lifting', body: ['Vorkhive runs all of the above from one platform: approved leave, claims and attendance feed gross pay, CPF is calculated automatically, employees self-serve their payslips, and the same data flows into IRAS-ready (IR8A) reporting. Most Singapore teams are live within a day.'] },
      ],
      faqHeading: 'Singapore payroll FAQ',
      faq: [
        { q: 'What are the steps to run payroll in Singapore?', a: 'Gather employee data, calculate gross pay, apply CPF and deductions, pay employees and issue itemised payslips, then keep records and file year-end reporting with IRAS (IR8A).' },
        { q: 'Are itemised payslips mandatory in Singapore?', a: 'Employers must issue itemised payslips to employees covered by the Employment Act. Vorkhive issues digital itemised payslips automatically.' },
        { q: 'How does Vorkhive simplify payroll?', a: 'It feeds approved leave, claims and attendance into gross pay, calculates CPF automatically, lets employees self-serve payslips, and produces IRAS-ready (IR8A) reporting from the same data.' },
      ],
      relatedHeading: 'Related',
      related: [{ label: 'Singapore payroll software', href: '/payroll-singapore' }, { label: 'CPF contribution rates', href: '/guides/cpf-contribution-rates-singapore' }, { label: 'Pricing', href: '/pricing' }],
      finalPrimary: 'Start free', finalSecondary: 'Talk to our team',
    },
    book: {
      seo: { title: 'Book a Vorkhive demo', description: 'Pick a date and time for a live Vorkhive HRMS demo. We confirm by email with a calendar invite. Singapore time.' },
      eyebrow: 'Book a demo',
      h1: 'Book your Vorkhive demo',
      lede: "Pick a date and a time that suits you — we'll confirm by email with a calendar invite. All times are Singapore time (SGT).",
      loading: 'Loading the calendar…',
      step1: '1 · Choose a date', step2: '2 · Choose a time', step3: '3 · Your details',
      selectDate: 'Select a date first.', checking: 'Checking availability…', booked: 'Booked',
      phName: 'Full name *', phEmail: 'Work email *', phCompany: 'Company', phPhone: 'Phone (optional)', phNotes: "Anything you'd like us to cover? (optional)",
      submit: 'Request demo', submitting: 'Booking…',
      errSlot: 'Please choose a date and time slot.', errName: 'Please enter your name and a valid email.',
      agreePre: "No charge — we'll confirm by email with a calendar invite. By requesting a demo, you agree to our ", agreeTerms: 'Terms of Service', agreeAnd: ' and ', agreePrivacy: 'Privacy Policy', agreePost: '.',
      doneTitle: 'Request received 🎉',
      doneBody: "Thanks! We've got your demo request for {date}, {period} (SGT). We'll email {email} to confirm with a calendar invite.",
    },
    contact: {
      seo: { title: 'Start your free trial | Vorkhive', description: 'Tell us about your team and we will set up your Vorkhive HRMS free trial.' },
      heading: 'Start Your Free Trial',
      sub: 'Fill out the form below and our team will get you set up with everything you need to streamline your operations.',
      lblName: 'Full Name *', lblEmail: 'Work Email *', lblCompany: 'Company Name *', lblSize: 'Company Size', lblMessage: 'How can Vorkhive help your team?',
      sizeSelect: 'Select size…', sizeUnit: 'employees',
      submit: 'Request Free Trial', submitting: 'Submitting…',
      agreePre: 'By submitting this form, you agree to our ', agreeTerms: 'Terms of Service', agreeAnd: ' and ', agreePrivacy: 'Privacy Policy', agreePost: '.',
      doneTitle: 'Request Received!',
      doneBody: 'Thank you for your interest in Vorkhive. Our team will review your information and contact you shortly to set up your free trial.',
      doneBtn: 'Return to Homepage',
    },
    platform: {
      seo: { title: 'The Vorkhive HRMS Platform — Leave, Payroll & People | Vorkhive', description: 'One Singapore HRMS for leave and self-service, payroll with CPF, and time and growth. See the Vorkhive platform that replaces spreadsheets and disconnected tools.' },
    },
    features: {
      seo: { title: 'Features — Why Singapore Teams Choose Vorkhive HRMS', description: 'Self-service for every employee, automatic CPF and statutory compliance, IRAS-ready filing, and one connected record for leave, claims, attendance and payroll.' },
    },
    pricing: {
      seo: { title: 'Pricing — Simple Per-User HRMS Plans | Vorkhive', description: 'Transparent per-user pricing for Vorkhive HRMS. Start free, scale to full payroll with CPF on the Growth plan, or talk to us about Enterprise.' },
    },
    faq: {
      seo: { title: 'Frequently Asked Questions | Vorkhive HRMS', description: 'Answers about Vorkhive HRMS — CPF and IRAS compliance, pricing, setup time, data security, and how leave, claims, attendance and payroll work together.' },
    },
    customers: {
      seo: { title: 'Customers — Singapore Teams Running on Vorkhive', description: 'See how Singapore SMEs use Vorkhive HRMS to run leave, claims, attendance and CPF payroll on one platform. Read what our customers say.' },
    },
  },
};

// Deep-merge overrides (from content.json) over the defaults. Arrays are
// replaced wholesale (so the admin owns list contents), objects merge by key.
export function mergeContent(base, override) {
  if (Array.isArray(override)) return override;
  if (override && typeof override === 'object' && !Array.isArray(base)) {
    const out = { ...base };
    for (const k of Object.keys(override)) {
      out[k] = k in base ? mergeContent(base[k], override[k]) : override[k];
    }
    return out;
  }
  return override === undefined ? base : override;
}
